import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { makeStyles } from '@material-ui/core/styles'

const useStyles = makeStyles((theme) => ({
  root: {
    background: '#1c1c1c',
    color: 'white',
    width: '100vw',
    height: '100vh',
    margin: '0',
    padding: '0',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center'
  },
  main: {
    margin: '0',
    padding: '0',
  },
  title: {
    margin: '0',
    padding: '0',
    fontFamily: 'Noto Sans JP'
  }
}))

export async function getServerSideProps() {
  const url = `https://api.themoviedb.org/3/movie/popular?api_key=50ee20a8e3da5025fd2012e0cc6f35ad&language=en-US&page=1&region=5016`;
  const res = await fetch(url);
  const data = await res.json();
  return {
    props: {
      data
    }
  }

}

 export default function Home({ data }) {
  const classes = useStyles();
  console.log(data)
  return (
    <div className={classes.root}>
      <Head>
        <title>IMDb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <h1 className={classes.title}>
          Welcome to IMDb!
        </h1>

     

       
      </main>
      </div>

  )
}
